### 本次代码为第三周逻辑回归阶段的练习code，任务：某学校根据学生两次测验的成绩来判断是否录取该学生，ex2data1.txt为往年学生的数据，根据此数据训练一个逻辑回归模型，可以根据两次测验成绩判断是否录取

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sys

ModuleNotFoundError: No module named 'numpy'

In [2]:
print(sys.path)

NameError: name 'sys' is not defined

In [2]:
path = 'ex2data1.txt' 
data = pd.read_csv(path, header=None, names=['Exam 1', 'Exam 2', 'Admitted'])
data.head()

Exam 1     Exam 2  Admitted
0  34.623660  78.024693         0
1  30.286711  43.894998         0
2  35.847409  72.902198         0
3  60.182599  86.308552         1
4  79.032736  75.344376         1

切割出X和y

In [3]:
data.insert(0, 'Ones', 1)
cols = data.shape[1]
X = data.iloc[:,0:cols-1]
y = data.iloc[:,cols-1:cols]
X = np.array(X.values)
y = np.array(y.values)
theta = np.zeros(3)

In [4]:
theta.shape

(3,)

In [5]:
X.shape

(100, 3)

In [6]:
y.shape

(100, 1)

###### 定义逻辑回归函数sigmoid

In [7]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [8]:
theta = np.matrix(theta)
theta = theta.T
theta.shape

(3, 1)

###### 计算cost

In [9]:
def compute_cost(X,theta,y):
    X = np.matrix(X)
    y = np.matrix(y)
    m = X.shape[0]#数据总行数
    s = sigmoid(np.dot(X,theta))
    # + 1e-6是为了避免计算log后的数值太大了，导致数据溢出，限制一下精度
    parm1 = np.multiply(-y,np.log(s + 1e-6))
    parm2 = np.multiply((1-y),np.log(1-s + 1e-6))
    return np.sum(parm1 - parm2) / m

In [10]:
cost = compute_cost(X,theta,y)
cost

0.6931451805619452

#### 下面进行梯度下降

采用向量化计算 𝑋.𝑇*(𝑆𝑖𝑔𝑚𝑜𝑖𝑑(𝑋𝜃)−𝑦)/m
X.T shape为（3，100），误差矩阵shape为（100，1）

In [11]:
def compute_gradient(X,y,theta):
    theta = np.matrix(theta)
    X = np.matrix(X)
    y = np.matrix(y)
    m = X.shape[0]
    gradients = np.dot(X.T,(sigmoid(np.dot(X,theta)) - y))/m
    return gradients

In [12]:
gradients = compute_gradient(X,y,theta)
gradients

matrix([[ -0.1       ],
        [-12.00921659],
        [-11.26284221]])

In [13]:
def update_parm(theta,gradients,alpha):
    theta = theta - np.dot(alpha,gradients)
    return theta

###### 进行批量梯度下降

In [16]:
def gradientDescent(X,y,theta,alpha,iters):
    cost_history = []
    theta_history = []
    theta_history.append(theta)
    for i in range(iters):
        cost = compute_cost(X,theta,y)
        gradients = compute_gradient(X,y,theta)
        theta = update_parm(theta,gradients,alpha)
        cost_history.append(cost)
        theta_history.append(theta)
    return cost_history, theta_history, theta

In [28]:
cost_history, theta_history, theta = gradientDescent(X,y,theta,0.0001,1000)

In [29]:
cost_history

[0.3066790380901545,
 0.3066790001560788,
 0.30667896222202856,
 0.3066789242880038,
 0.30667888635400453,
 0.30667884842003074,
 0.30667881048608253,
 0.30667877255215964,
 0.3066787346182624,
 0.3066786966843905,
 0.30667865875054423,
 0.30667862081672337,
 0.306678582882928,
 0.30667854494915814,
 0.3066785070154139,
 0.30667846908169494,
 0.30667843114800153,
 0.30667839321433366,
 0.30667835528069126,
 0.3066783173470744,
 0.3066782794134829,
 0.30667824147991696,
 0.3066782035463766,
 0.3066781656128616,
 0.3066781276793722,
 0.3066780897459082,
 0.3066780518124697,
 0.30667801387905674,
 0.3066779759456692,
 0.30667793801230725,
 0.3066779000789707,
 0.3066778621456596,
 0.30667782421237405,
 0.306677786279114,
 0.30667774834587946,
 0.3066777104126704,
 0.3066776724794868,
 0.3066776345463287,
 0.3066775966131961,
 0.30667755868008895,
 0.3066775207470073,
 0.3066774828139512,
 0.3066774448809205,
 0.30667740694791545,
 0.30667736901493575,
 0.3066773310819816,
 0.3066772931490

In [30]:
theta_history

[matrix([[-7.93613597],
         [ 0.06928428],
         [ 0.06283008]]),
 matrix([[-7.93613791],
         [ 0.06928429],
         [ 0.0628301 ]]),
 matrix([[-7.93613986],
         [ 0.06928431],
         [ 0.06283011]]),
 matrix([[-7.93614181],
         [ 0.06928433],
         [ 0.06283013]]),
 matrix([[-7.93614376],
         [ 0.06928434],
         [ 0.06283014]]),
 matrix([[-7.9361457 ],
         [ 0.06928436],
         [ 0.06283016]]),
 matrix([[-7.93614765],
         [ 0.06928437],
         [ 0.06283017]]),
 matrix([[-7.9361496 ],
         [ 0.06928439],
         [ 0.06283019]]),
 matrix([[-7.93615155],
         [ 0.0692844 ],
         [ 0.06283021]]),
 matrix([[-7.93615349],
         [ 0.06928442],
         [ 0.06283022]]),
 matrix([[-7.93615544],
         [ 0.06928443],
         [ 0.06283024]]),
 matrix([[-7.93615739],
         [ 0.06928445],
         [ 0.06283025]]),
 matrix([[-7.93615934],
         [ 0.06928446],
         [ 0.06283027]]),
 matrix([[-7.93616128],
         [ 0.0

###### 最终优化后获得的参数

In [39]:
theta

matrix([[-7.93808319],
        [ 0.06929945],
        [ 0.06284549]])

In [40]:
cost = compute_cost(X,theta,y)
cost

0.30664111674261696

###### 编写一个函数进行预测，并计算准确率

当 ℎ𝜃
 大于等于0.5时，预测 y=1

当 ℎ𝜃
 小于0.5时，预测 y=0 。

In [37]:
def predict(theta, X):
    probability = sigmoid(np.dot(X,theta))
    return [1 if x >= 0.5 else 0 for x in probability]

In [38]:
predictions = predict(theta, X)
correct = [1 if ((a == 1 and b == 1) or (a == 0 and b == 0)) else 0 for (a, b) in zip(predictions, y)]
accuracy = (sum(map(int, correct)) % len(correct))
print ('accuracy = {0}%'.format(accuracy))

accuracy = 92%
