In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
path =  'ex1data1.txt'
data = pd.read_csv(path, header=None, names=['Population', 'Profit'])
data.head()

In [ ]:
data.insert(0, 'Ones', 1)#添加一列方便向量运算

In [ ]:
data.head()#观察前五行

In [ ]:
#从数据集中提取出X和y
cols = data.shape[1]
X = data.iloc[:,0:cols-1]#去掉最后一列得到X
y = data.iloc[:,cols-1:cols]#保留最后一列得到y

In [ ]:
X.head()

In [ ]:
y.head()

In [ ]:
theta = np.random.rand(2,1)#随机生成theta，即w和b

In [ ]:
theta

In [ ]:
#X，y转为矩阵
X = np.matrix(X.values)
y = np.matrix(y.values)

In [ ]:
#计算线性模型预测出来的y
def compute_predict_y(X,theta):
    predict_y = np.dot(X,theta)
    return predict_y

In [ ]:
predict_y = compute_predict_y(X,theta)
predict_y

In [ ]:
#计算cost
def computeCost(y,predict_y):
    m = y.shape[0]
    cost = np.sum(np.power((y-predict_y),2))/(2*m)
    return cost

In [ ]:
print(computeCost(y,predict_y))

In [34]:
#计算梯度,这个是比较难的点
def compute_gradient(X,y,predict_y):
    m = X.shape[0]
    #计算两个参数的梯度,矩阵乘法!!
    #X.T为2行m列，第一行代表自变量x1，第二行是常数1
    gradients = np.random.rand(2,1)
    gradients = np.dot(X.T,(predict_y - y))/m
    return gradients

In [35]:
print(compute_gradient(X,y,predict_y))

[[ -0.76162667]
 [-15.81736674]]


In [36]:
def update_parm(theta,gradients,alpha):
    #更新参数
    theta = theta - np.dot(alpha,gradients)
    return theta

In [46]:
#迭代梯度下降
def gradientDescent(X,y,theta,alpha,iters):
    cost_history = []
    theta_history = []
    theta_history.append(theta)
    for i in range(iters):
        predict_y = compute_predict_y(X,theta)
        cost = computeCost(y,predict_y)
        gradients = compute_gradient(X,y,predict_y)
        theta = update_parm(theta,gradients,alpha)
        cost_history.append(cost)
        theta_history.append(theta)
    return cost_history, theta_history, theta

In [47]:
cost_history, theta_history, theta = gradientDescent(X,y,theta,0.001,1000)

In [45]:
cost_history

[5.787828461494544,
 5.7873559149879625,
 5.7868835388281,
 5.786411332953546,
 5.785939297302916,
 5.785467431814846,
 5.7849957364279945,
 5.784524211081043,
 5.784052855712694,
 5.783581670261672,
 5.783110654666724,
 5.7826398088666195,
 5.782169132800152,
 5.781698626406131,
 5.781228289623395,
 5.780758122390798,
 5.780288124647223,
 5.779818296331568,
 5.7793486373827605,
 5.778879147739743,
 5.778409827341483,
 5.777940676126971,
 5.7774716940352215,
 5.777002881005262,
 5.77653423697615,
 5.776065761886966,
 5.775597455676806,
 5.775129318284793,
 5.774661349650071,
 5.774193549711802,
 5.773725918409176,
 5.773258455681401,
 5.772791161467709,
 5.772324035707353,
 5.771857078339607,
 5.771390289303766,
 5.7709236685391545,
 5.770457215985106,
 5.769990931580985,
 5.769524815266179,
 5.769058866980091,
 5.768593086662148,
 5.7681274742518,
 5.7676620296885215,
 5.767196752911804,
 5.766731643861162,
 5.766266702476136,
 5.765801928696279,
 5.765337322461175,
 5.764872883710426

In [48]:
theta_history

[matrix([[-0.72716099],
         [ 0.87471141]]),
 matrix([[-0.72773216],
         [ 0.87476879]]),
 matrix([[-0.72830323],
         [ 0.87482616]]),
 matrix([[-0.7288742 ],
         [ 0.87488352]]),
 matrix([[-0.72944506],
         [ 0.87494087]]),
 matrix([[-0.73001583],
         [ 0.87499821]]),
 matrix([[-0.73058649],
         [ 0.87505554]]),
 matrix([[-0.73115704],
         [ 0.87511285]]),
 matrix([[-0.7317275 ],
         [ 0.87517016]]),
 matrix([[-0.73229785],
         [ 0.87522746]]),
 matrix([[-0.7328681 ],
         [ 0.87528475]]),
 matrix([[-0.73343824],
         [ 0.87534202]]),
 matrix([[-0.73400828],
         [ 0.87539929]]),
 matrix([[-0.73457822],
         [ 0.87545655]]),
 matrix([[-0.73514806],
         [ 0.87551379]]),
 matrix([[-0.73571779],
         [ 0.87557103]]),
 matrix([[-0.73628743],
         [ 0.87562826]]),
 matrix([[-0.73685696],
         [ 0.87568547]]),
 matrix([[-0.73742638],
         [ 0.87574268]]),
 matrix([[-0.73799571],
         [ 0.87579987]]),


In [49]:
theta

matrix([[-1.249857  ],
        [ 0.92722189]])